package cl.demochl.model;
// Generated 05-01-2020 18:15:21 by Hibernate Tools 4.3.1



/**
 * FacturaHasProducto generated by hbm2java
 */
public class FacturaHasProducto  implements java.io.Serializable {


     private FacturaHasProductoId id;
     private Factura factura;
     private Producto producto;
     private Integer cantidad;
     private Float precioTotal;

    public FacturaHasProducto() {
    }

	
    public FacturaHasProducto(FacturaHasProductoId id, Factura factura, Producto producto) {
        this.id = id;
        this.factura = factura;
        this.producto = producto;
    }
    public FacturaHasProducto(FacturaHasProductoId id, Factura factura, Producto producto, Integer cantidad, Float precioTotal) {
       this.id = id;
       this.factura = factura;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioTotal = precioTotal;
    }
   
    public FacturaHasProductoId getId() {
        return this.id;
    }
    
    public void setId(FacturaHasProductoId id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Float getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(Float precioTotal) {
        this.precioTotal = precioTotal;
    }




}


