package cl.demochl.model;
// Generated 05-01-2020 18:15:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer numFactura;
     private Cliente cliente;
     private Date fecha;
     private Float subtotal;
     private Float iva;
     private Float total;
     private Set<FacturaHasProducto> facturaHasProductos = new HashSet<FacturaHasProducto>(0);

    public Factura() {
    }

	
    public Factura(Cliente cliente) {
        this.cliente = cliente;
    }
    public Factura(Cliente cliente, Date fecha, Float subtotal, Float iva, Float total, Set<FacturaHasProducto> facturaHasProductos) {
       this.cliente = cliente;
       this.fecha = fecha;
       this.subtotal = subtotal;
       this.iva = iva;
       this.total = total;
       this.facturaHasProductos = facturaHasProductos;
    }
   
    public Integer getNumFactura() {
        return this.numFactura;
    }
    
    public void setNumFactura(Integer numFactura) {
        this.numFactura = numFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Float subtotal) {
        this.subtotal = subtotal;
    }
    public Float getIva() {
        return this.iva;
    }
    
    public void setIva(Float iva) {
        this.iva = iva;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }
    public Set<FacturaHasProducto> getFacturaHasProductos() {
        return this.facturaHasProductos;
    }
    
    public void setFacturaHasProductos(Set<FacturaHasProducto> facturaHasProductos) {
        this.facturaHasProductos = facturaHasProductos;
    }




}


